# Generated by Django 5.2.6 on 2025-09-10 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the T-shirt.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the T-shirt.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the T-shirt in INR.', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='The number of units available in stock.')),
                ('image', models.ImageField(help_text='An image of the T-shirt.', upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the product was added to the store.')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the order was created.')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The total cost of all items in the order.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The current status of the order.', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='The order ID generated by Razorpay.', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='The payment ID from a successful Razorpay transaction.', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='The signature returned by Razorpay for payment verification.', max_length=200, null=True)),
                ('customer', models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of units of the product ordered.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of a single unit of the product at the time the order was placed.', max_digits=10)),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(help_text='The product being ordered. PROTECT prevents deleting a product that has been ordered.', on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
    ]
