# Generated by Django 5.2.6 on 2025-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_is_bestseller_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Identifies if the product is a custom design by a user.'),
        ),
    ]
