from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    """
    Represents a T-shirt product available for sale in the store.
    Each product has a name, description, price, stock level, and an image.
    """
    name = models.CharField(max_length=255, help_text="The name of the T-shirt.")
    description = models.TextField(help_text="A detailed description of the T-shirt.")
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text="The price of the T-shirt in INR.")
    stock = models.PositiveIntegerField(default=0, help_text="The number of units available in stock.")
    image = models.ImageField(upload_to='products/', help_text="An image of the T-shirt.")
    created_at = models.DateTimeField(auto_now_add=True, help_text="The date and time the product was added to the store.")
    
    # New fields for categorizing products
    is_featured = models.BooleanField(default=False, help_text="Is this product featured on the homepage?")
    is_trending = models.BooleanField(default=False, help_text="Is this a trending product?")
    is_bestseller = models.BooleanField(default=False, help_text="Is this a best-selling product?")
    is_custom = models.BooleanField(default=False, help_text="Identifies if the product is a custom design by a user.")

    def __str__(self):
        return f"{self.name} - ₹{self.price}"

class Order(models.Model):
    """
    Represents a single order made by a customer.
    It links to the customer, tracks the order status, total price, and payment details from Razorpay.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('PROCESSING', 'Processing'),
        ('SHIPPED', 'Shipped'),
        ('DELIVERED', 'Delivered'),
        ('CANCELLED', 'Cancelled'),
    ]

    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders', help_text="The user who placed the order.")
    created_at = models.DateTimeField(auto_now_add=True, help_text="The timestamp when the order was created.")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, help_text="The total cost of all items in the order.")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING', help_text="The current status of the order.")
    
    # Razorpay payment details
    razorpay_order_id = models.CharField(max_length=100, blank=True, null=True, help_text="The order ID generated by Razorpay.")
    razorpay_payment_id = models.CharField(max_length=100, blank=True, null=True, help_text="The payment ID from a successful Razorpay transaction.")
    razorpay_signature = models.CharField(max_length=200, blank=True, null=True, help_text="The signature returned by Razorpay for payment verification.")

    def __str__(self):
        return f"Order #{self.id} by {self.customer.username} - {self.status}"

class OrderItem(models.Model):
    """
    Represents a single product within an order (a line item).
    This model connects a specific product to an order and stores the quantity and the price at the time of purchase.
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', help_text="The order this item belongs to.")
    product = models.ForeignKey(Product, on_delete=models.PROTECT, help_text="The product being ordered. PROTECT prevents deleting a product that has been ordered.")
    quantity = models.PositiveIntegerField(help_text="The number of units of the product ordered.")
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text="The price of a single unit of the product at the time the order was placed.")

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Order #{self.order.id}"
