from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    RegisterView,
    LoginView,
    ProductViewSet,
    OrderViewSet,
    CreateRazorpayOrderView,
    VerifyPaymentView,
    AdminDashboardStats,
    OrderListAdminView,
    UserListAdminView,
    # ADDED: New import for the detail view
    UserDetailAdminView,
    UpdateOrderStatusView
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')
router.register(r'orders', OrderViewSet, basename='order')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),

    # Authentication URLs
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    
    # JWT Token URLs
    path('auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Razorpay Payment URLs
    path('payment/create-order/', CreateRazorpayOrderView.as_view(), name='create-razorpay-order'),
    path('payment/verify/', VerifyPaymentView.as_view(), name='verify-payment'),

    # Admin Dashboard URL
    path('admin/stats/', AdminDashboardStats.as_view(), name='admin-stats'),
    
    # ADMIN USER PATHS
    path('admin/users/', UserListAdminView.as_view(), name='admin-user-list'),
    # ADDED: Detail path for retrieving, updating, and deleting a single user.
    # The frontend calls this URL: '/admin/users/<int:pk>/'
    path('admin/users/<int:pk>/', UserDetailAdminView.as_view(), name='admin-user-detail'),
    
    # ADMIN ORDER PATHS
    path('admin/orders/', OrderListAdminView.as_view(), name='admin-order-list'),
    path('admin/orders/<int:order_id>/status/', UpdateOrderStatusView.as_view(), name='update-order-status'),
]